"""empty message

Revision ID: 3e3fba420067
Revises: 745c08f25df
Create Date: 2016-02-03 08:41:41.049048

"""

# revision identifiers, used by Alembic.
revision = '3e3fba420067'
down_revision = '745c08f25df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.add_column(u'users', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column(u'users', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column(u'users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_column(u'users', 'role_id')
    op.drop_column(u'users', 'last_name')
    op.drop_column(u'users', 'first_name')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    ### end Alembic commands ###
