"""empty message

Revision ID: 745c08f25df
Revises: None
Create Date: 2016-02-02 18:40:15.607214

"""

# revision identifiers, used by Alembic.
revision = '745c08f25df'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    with op.batch_alter_table('users'):
        op.create_table('users',
                        sa.Column('id', sa.Integer(),
                                  nullable=False),
                        sa.Column(
                            'email', sa.String(length=64), nullable=True),
                        sa.Column(
                            'username', sa.String(length=64), nullable=True),
                        sa.Column(
                            'password_hash', sa.String(length=128),
                            nullable=True
                        ),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('email')
                        )
        op.create_index(
            'ix_users_username', 'users', ['username'], unique=True)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', 'users')
    op.drop_table('users')
    ### end Alembic commands ###
